In [88]:
import pandas as pd
from random import sample
import string
import re
my_punctuation = string.punctuation.replace("-", "")

In [96]:
df = pd.read_csv("../data/processed/validated_drugname_list.csv", usecols=["drugname"])
arr = df.to_numpy().astype('str').flatten()

In [97]:
p_arr = [a.lower() for a in arr]
p_arr = [re.sub("[\(\[].*?[\)\]]", "", a) for a in p_arr]
p_arr = [a.translate(str.maketrans(' ', ' ', my_punctuation)) for a in p_arr]
pp_arr = []
for a in p_arr:
    result = ''.join([i for i in a if not i.isdigit()])
    pp_arr.append(result)
# pp_arr = [a.replace(' mg ', '') for a in pp_arr]
# pp_arr = [a.replace(' ml ', '') for a in pp_arr]
# pp_arr = [a.rstrip() for a in pp_arr]
ppp_arr = [" ".join(a.split()) for a in pp_arr]
ppp_arr = [a.rstrip(string.punctuation) for a in ppp_arr]

In [103]:
sample(ppp_arr, 10)

['apomidodrine',
 'fluconazole mg',
 'tramadol hco',
 'aredia',
 'ibugesic plus',
 'lamotrigineer hr tablet qd',
 'meropur',
 'sol medrol',
 'ezetimibe simvastatin',
 'fluorouracil cream usp']

In [98]:
df = pd.read_csv("../data/processed/validated_drugname_list.csv", index_col=False)

In [99]:
df["clean_drugname"] = pd.Series(ppp_arr)

In [100]:
df = df.rename(columns={"drugname":"old_drugname", "clean_drugname":"drugname"})

In [101]:
df.to_csv("../data/processed/validated_drugname_list_with_cleaned_col.csv", index=False)

In [102]:
df

,primaryid,caseid,drug_seq,role_cod,old_drugname,val_vbm,route,nda_num,origin,prod_ai,info_scores,drugname
0,116499822,11649982,1,PS,OXYCONTIN,1,Oral,22272.0,DRUG16Q2.txt,OXYCODONE HYDROCHLORIDE,0,oxycontin
1,175577371,17557737,1,PS,BEOVU,1,Ophthalmic,761125.0,DRUG20Q1.txt,BROLUCIZUMAB-DBLL,0,beovu
2,117533221,11753322,1,PS,NEXPLANON,1,Subdermal,21529.0,DRUG15Q4.txt,ETONOGESTREL,0,nexplanon
3,117533231,11753323,1,PS,COSENTYX,1,Unknown,125504.0,DRUG15Q4.txt,SECUKINUMAB,0,cosentyx
4,117533241,11753324,1,PS,SPIRIVA,1,Respiratory (inhalation),21395.0,DRUG15Q4.txt,TIOTROPIUM BROMIDE MONOHYDRATE,0,spiriva
...,...,...,...,...,...,...,...,...,...,...,...,...
227674,95974611,9597461,9,SS,HYDROCORT /00028604/,1,NaN,NaN,DRUG13Q4.txt,NaN,2,hydrocort
227675,95971591,9597159,2,C,Clonipine,1,UNKNOWN,NaN,DRUG13Q4.txt,NaN,2,clonipine
227676,95971584,9597158,4,C,Klonpin,1,NaN,NaN,DRUG13Q4.txt,NaN,2,klonpin
227677,95970781,9597078,3,I,ETAMBUTOL /00022301/,1,UNKNOWN,NaN,DRUG13Q4.txt,NaN,2,etambutol
227678,95970611,9597061,4,C,AMLOPIC,1,ORAL,NaN,DRUG13Q4.txt,NaN,2,amlopic