In [1]:
import pandas as pd

In [6]:
# Column information obtained from https://www.nlm.nih.gov/research/umls/rxnorm/docs/techdoc.html#conso
column_names = ["RXCUI", "LAT", "TS", "LUI", "STT", "SUI", "ISPREF", "RXAUI", "SAUI", "SCUI",
                "SDUI", "SAB", "TTY", "CODE", "STR", "SRL", "SUPPRESS", "CVF"]
df = pd.read_csv("../data/dictionaries/RXNCONSO.RRF", sep="|", header=None, names=column_names, index_col=False)

### The approximate matching authors from RxNorm wrote in their 2011 paper that their approach consisted of selecting all rows where Ingredient (IN), Precise Ingredient (PIN) or Brand Name (BN) was the TTY (Term type in source). They subsequently created a list from all the STR columns in the row, and used this for the identification of the drug token in the input.

In [7]:
df.head()

,RXCUI,LAT,TS,LUI,STT,SUI,ISPREF,RXAUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF
0,38,ENG,NaN,NaN,NaN,NaN,NaN,829,829,38,NaN,RXNORM,BN,38,Parlodel,NaN,N,4096
1,44,ENG,NaN,NaN,NaN,NaN,NaN,12251526,12251526,44,NaN,RXNORM,IN,44,mesna,NaN,N,4096
2,44,ENG,NaN,NaN,NaN,NaN,NaN,2798745,2798745,44,NaN,MTHSPL,SU,NR7O1405Q9,mesna,NaN,N,4096
3,44,ENG,NaN,NaN,NaN,NaN,NaN,2982613,2982613,44,NaN,MTHSPL,SU,NR7O1405Q9,MESNA,NaN,N,4096
4,61,ENG,NaN,NaN,NaN,NaN,NaN,12254378,12254378,61,NaN,RXNORM,IN,61,beta-alanine,NaN,N,4096

In [11]:
p_df = df[(df["TTY"] == "BN") | (df["TTY"] == "IN") | (df["TTY"] == "PIN")]

In [16]:
drug_detection_list = p_df["STR"].sort_values(ascending=True)

In [17]:
drug_detection_list.to_csv("../data/dictionaries/drug_detection_list_peters.csv", header=False, index=False)