In [1]:
import pandas as pd

In [8]:
leg = pd.read_csv("../data/processed/legacy_set_fixed.csv", low_memory=False)

In [9]:
leg = leg.drop("Unnamed: 12", axis=1)

In [10]:
rest = pd.read_csv("../data/processed/rest_banda_set.csv", low_memory=False)

In [20]:
leg.head()

,ISR,DRUG_SEQ,ROLE_COD,DRUGNAME,VAL_VBM,ROUTE,DOSE_VBM,DECHAL,RECHAL,LOT_NUM,EXP_DT,NDA_NUM,origin
0,4204616,1004278786,PS,"MIFEPRISTONE TABLETS, 200 MG (DANCO LABS)",2,ORAL,"200 MG, ORAL",D,D,20002,20020331.0,20687.0,DRUG04Q1.TXT
1,4204616,1004279849,SS,MISOPROSTOL,1,VAGINAL,"800 MCG, VAGINAL",D,D,C2001748,NaN,NaN,DRUG04Q1.TXT
2,4214534,1004308602,PS,OXYCODONE HCL,1,NaN,NaN,D,D,NaN,NaN,20553.0,DRUG04Q1.TXT
3,4214534,1004349743,SS,"HYDROCODONE BITARTRATE (SIMILAR TO IND 59,175)...",2,NaN,NaN,D,D,NaN,NaN,NaN,DRUG04Q1.TXT
4,4214534,1004349748,C,ANALGESICS ( ),2,NaN,NaN,U,U,NaN,NaN,NaN,DRUG04Q1.TXT

In [30]:
leg_part = leg[["DRUGNAME", "NDA_NUM", "origin"]]
rest_part = rest[["drugname", "nda_num", "prod_ai", "origin"]]
leg_part.columns = ["drugname", "nda_num", "origin"]

In [32]:
dfs = [leg_part, rest_part]
banda_set_df = pd.concat(dfs, axis=0, ignore_index=True)

In [34]:
banda_set_df.to_csv("../data/processed/banda_set.csv", index=False)

In [35]:
banda_set_df.head()

,drugname,nda_num,origin,prod_ai
0,"MIFEPRISTONE TABLETS, 200 MG (DANCO LABS)",20687.0,DRUG04Q1.TXT,NaN
1,MISOPROSTOL,NaN,DRUG04Q1.TXT,NaN
2,OXYCODONE HCL,20553.0,DRUG04Q1.TXT,NaN
3,"HYDROCODONE BITARTRATE (SIMILAR TO IND 59,175)...",NaN,DRUG04Q1.TXT,NaN
4,ANALGESICS ( ),NaN,DRUG04Q1.TXT,NaN